[package]
name = "gmt-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goodmorning-services = { git = "https://github.com/GoodMorning-Network/services", rev = "90509fe" }
goodmorning-bindings = { git = "https://github.com/GoodMorning-Network/rust-bindings", rev = "eaa9cee"}
# goodmorning-services = { path = "../goodmorning-services" }
# goodmorning-bindings = { path = "../rust-bindings" }
actix-web = {version = "4.3", features = ["rustls"]}
rustls = "0.20"
rustls-pemfile = "1"
tokio = {version = "1.26", features = ["fs"]}
serde = "1.0"
actix-files = "0.6"
mongodb = "2.5"
sudo = "0.6"
dotenv = "0.15"
simplelog = "0.12"
log = "0.4"
chrono = "0.4"
yew = { version = "0.20", features = ["ssr"] }
once_cell = "1.18"
