[package]
name = "gmt-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# goodmorning-services = { git = "https://github.com/GoodMorning-Network/services" }
goodmorning-services = { path = "../goodmorning-services" }
actix-web = "4.3"
tokio = {version = "1.26", features = ["fs"]}
serde = "1.0"
actix-files = "0.6"
yew = "0.20"
